### ISSUE TITLE
Running from dotnet test, what is the correct syntax 

### ISSUE THREAD

**Issue by rick-casady-ah** [brendanconnolly/Xunit.Categories#15]
What would be the syntax for running [Bug] or[Bug("101")] attributes from dotnet test
 
Its not working for me but I thought it would be:
dotnet test --filter Category=bug
dotnet test --filter Category=bug=101

I'm using dotnetcore 2.1, xunit 2.4.1

**Comment by brendanconnolly** [comment]
I updated the readme, I think the issue is your filter value needs to be in quotes

```
dotnet test --filter "Category=Bug"
dotnet test --filter "Bug=777"
```
