### ISSUE TITLE
Cant't use xunit.categories with xunit.assert.source

### ISSUE THREAD

**Issue by WalkerCodeRanger** [brendanconnolly/Xunit.Categories#16]
The recommended way of extending the xUnit asserts is to reference the `xunit.assert.source` NuGet package. When you do that, you can't use the `xunit` package anymore because it pulls in `xunit.assert` which conflicts. Instead, you have to reference `xunit.core` etc.

I'm assuming the `xunit.categories` package doesn't actually depend on all of the `xunit` package. You should be able to reference only `xunit.core`. That would allow people to use it at the same time as `xunit.assert.source`.

**Comment by brendanconnolly** [comment]
thanks for reporting this I'll take a look

**Comment by Chaosflo** [comment]
Any work on this?
