### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by Tanzy** [brendanconnolly/Xunit.Categories#18]
Do you have any plans on updating the Nuget package in the store?

https://www.nuget.org/packages/xunit.categories/

Shows the latest version is 2.0.4 that was last updated in 2018, and I can see that the code has been updated since then.

**Comment by zetroot** [comment]
@brendanconnolly what about using github actions as CI? They are free, quite simple and secure - no need to share your nuget token.

**Comment by zetroot** [comment]
And, of course, i would be glad to help you with it, if you need it.
@brendanconnolly

**Comment by Tanzy** [comment]
I’ve ended up creating my own NuGet package to do this

**Comment by zetroot** [comment]
Have you set up github's CI for it?

**Comment by Tanzy** [comment]
Done one that will do me for now

**Comment by brendanconnolly** [comment]
actually was planning to get to github actions, but not been able to get to it. I would love the help @zetroot 

have a starting point action merged in, it just ran successfully. Hope to see the nuget package is updated shortly

**Comment by brendanconnolly** [comment]
@zetroot package is updated on nuget now, care to give it a try?

**Comment by zetroot** [comment]
@brendanconnolly i won't change source code or some other way affect package functionality.
I meant develop some workflows to automatically smoke-test all incoming PRs, and build-test-publish nuget on push to master. So, there is no need to remove the listed package.

Btw, if there will be a new build (may be with new code inside it), but package version won't change - how will nuget.org behave? It seems to me nothing bad will happen. Just new instance of package will be delivered during restore step.

Or what do you mean? Sorry, for misunderstanding, my English may fail time to time (working on it, lol).

**Comment by brendanconnolly** [comment]
I added an action that on merge to master will automatically publish an update to nuget.  For new prs the `.csproj` file will need to be updated with a new version and release notes. It could be improved and made more robust, but this seemed like a good starting place.  PR here https://github.com/brendanconnolly/Xunit.Categories/pull/19

A new build published today with all the latest changes. 

Would love more workflows so feel free to open up a pr, thanks for being involved
