### ISSUE TITLE
multiple attribute in the test

### ISSUE THREAD

**Issue by madagama89** [brendanconnolly/Xunit.Categories#21]
Hello, I would like to know if it is possible to combine several attributes in the same test, for example:

        [Fact]
        [Bug(777)]
	[Feature(1111)]
	[TestCase(2222)]
	[Exploratory]
        public void TestBugWithId()
        {
            throw new NotImplementedException("I've got your number");
        }

Thanks

**Comment by brendanconnolly** [comment]
yes, you should be able to add multiple attributes to suit you needs 😄
