### ISSUE TITLE
suggestion: SystemTest attribute

### ISSUE THREAD

**Issue by rsouthworth** [brendanconnolly/Xunit.Categories#8]
Would it be possible to add a SystemTest attribute please? This is more black box, high level, and stress testing of a complete running application different to an IntegrationTest.

**Comment by brendanconnolly** [comment]
Added, I'll update the nuget package shortly. 

thanks for the suggestion!

**Comment by brendanconnolly** [comment]
nuget package is validating now. will be in v2.0.3

**Comment by rsouthworth** [comment]
Great. Thanks !
